// Code generated by MockGen. DO NOT EDIT.
// Source: /home/jasim/CityVibe-Ecommerce-CleanCode-Project/pkg/repository/interface/category.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	domain "github.com/14jasimmtp/CityVibe-Project-Clean-Architecture/pkg/domain"
	models "github.com/14jasimmtp/CityVibe-Project-Clean-Architecture/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockCategoryRepo is a mock of CategoryRepo interface.
type MockCategoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryRepoMockRecorder
}

// MockCategoryRepoMockRecorder is the mock recorder for MockCategoryRepo.
type MockCategoryRepoMockRecorder struct {
	mock *MockCategoryRepo
}

// NewMockCategoryRepo creates a new mock instance.
func NewMockCategoryRepo(ctrl *gomock.Controller) *MockCategoryRepo {
	mock := &MockCategoryRepo{ctrl: ctrl}
	mock.recorder = &MockCategoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryRepo) EXPECT() *MockCategoryRepoMockRecorder {
	return m.recorder
}

// AddCategory mocks base method.
func (m *MockCategoryRepo) AddCategory(category models.Category) (domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCategory", category)
	ret0, _ := ret[0].(domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCategory indicates an expected call of AddCategory.
func (mr *MockCategoryRepoMockRecorder) AddCategory(category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCategory", reflect.TypeOf((*MockCategoryRepo)(nil).AddCategory), category)
}

// CheckCategory mocks base method.
func (m *MockCategoryRepo) CheckCategory(current string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCategory", current)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCategory indicates an expected call of CheckCategory.
func (mr *MockCategoryRepoMockRecorder) CheckCategory(current interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCategory", reflect.TypeOf((*MockCategoryRepo)(nil).CheckCategory), current)
}

// DeleteCategory mocks base method.
func (m *MockCategoryRepo) DeleteCategory(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockCategoryRepoMockRecorder) DeleteCategory(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockCategoryRepo)(nil).DeleteCategory), id)
}

// GetCategory mocks base method.
func (m *MockCategoryRepo) GetCategory() ([]domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory")
	ret0, _ := ret[0].([]domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockCategoryRepoMockRecorder) GetCategory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockCategoryRepo)(nil).GetCategory))
}

// UpdateCategory mocks base method.
func (m *MockCategoryRepo) UpdateCategory(current, new string) (domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", current, new)
	ret0, _ := ret[0].(domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockCategoryRepoMockRecorder) UpdateCategory(current, new interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockCategoryRepo)(nil).UpdateCategory), current, new)
}
